// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.etermax.tools.nationality;


public final class Nationality extends Enum
{

    private static final Nationality $VALUES[];
    public static final Nationality AD;
    public static final Nationality AE;
    public static final Nationality AF;
    public static final Nationality AG;
    public static final Nationality AI;
    public static final Nationality AL;
    public static final Nationality AM;
    public static final Nationality AO;
    public static final Nationality AR;
    public static final Nationality AS;
    public static final Nationality AT;
    public static final Nationality AU;
    public static final Nationality AW;
    public static final Nationality AX;
    public static final Nationality AZ;
    public static final Nationality BA;
    public static final Nationality BB;
    public static final Nationality BD;
    public static final Nationality BE;
    public static final Nationality BF;
    public static final Nationality BG;
    public static final Nationality BH;
    public static final Nationality BI;
    public static final Nationality BJ;
    public static final Nationality BL;
    public static final Nationality BM;
    public static final Nationality BN;
    public static final Nationality BO;
    public static final Nationality BQ;
    public static final Nationality BR;
    public static final Nationality BS;
    public static final Nationality BT;
    public static final Nationality BW;
    public static final Nationality BY;
    public static final Nationality BZ;
    public static final Nationality CA;
    public static final Nationality CD;
    public static final Nationality CF;
    public static final Nationality CG;
    public static final Nationality CH;
    public static final Nationality CI;
    public static final Nationality CL;
    public static final Nationality CM;
    public static final Nationality CN;
    public static final Nationality CO;
    public static final Nationality CR;
    public static final Nationality CU;
    public static final Nationality CV;
    public static final Nationality CW;
    public static final Nationality CY;
    public static final Nationality CZ;
    public static final Nationality DE;
    public static final Nationality DJ;
    public static final Nationality DK;
    public static final Nationality DM;
    public static final Nationality DO;
    public static final Nationality DZ;
    public static final Nationality EC;
    public static final Nationality EE;
    public static final Nationality EG;
    public static final Nationality EH;
    public static final Nationality ER;
    public static final Nationality ES;
    public static final Nationality ET;
    public static final Nationality FI;
    public static final Nationality FJ;
    public static final Nationality FM;
    public static final Nationality FO;
    public static final Nationality FR;
    public static final Nationality GA;
    public static final Nationality GB;
    public static final Nationality GD;
    public static final Nationality GE;
    public static final Nationality GF;
    public static final Nationality GG;
    public static final Nationality GH;
    public static final Nationality GI;
    public static final Nationality GL;
    public static final Nationality GM;
    public static final Nationality GN;
    public static final Nationality GP;
    public static final Nationality GQ;
    public static final Nationality GR;
    public static final Nationality GT;
    public static final Nationality GU;
    public static final Nationality GW;
    public static final Nationality GY;
    public static final Nationality HK;
    public static final Nationality HN;
    public static final Nationality HR;
    public static final Nationality HT;
    public static final Nationality HU;
    public static final Nationality ID;
    public static final Nationality IE;
    public static final Nationality IL;
    public static final Nationality IN;
    public static final Nationality IQ;
    public static final Nationality IR;
    public static final Nationality IS;
    public static final Nationality IT;
    public static final Nationality JE;
    public static final Nationality JM;
    public static final Nationality JO;
    public static final Nationality JP;
    public static final Nationality KE;
    public static final Nationality KG;
    public static final Nationality KH;
    public static final Nationality KI;
    public static final Nationality KM;
    public static final Nationality KN;
    public static final Nationality KP;
    public static final Nationality KR;
    public static final Nationality KW;
    public static final Nationality KZ;
    public static final Nationality LA;
    public static final Nationality LB;
    public static final Nationality LC;
    public static final Nationality LI;
    public static final Nationality LK;
    public static final Nationality LR;
    public static final Nationality LS;
    public static final Nationality LT;
    public static final Nationality LU;
    public static final Nationality LV;
    public static final Nationality LY;
    public static final Nationality MA;
    public static final Nationality MC;
    public static final Nationality MD;
    public static final Nationality ME;
    public static final Nationality MG;
    public static final Nationality MH;
    public static final Nationality MK;
    public static final Nationality ML;
    public static final Nationality MM;
    public static final Nationality MN;
    public static final Nationality MO;
    public static final Nationality MR;
    public static final Nationality MT;
    public static final Nationality MU;
    public static final Nationality MV;
    public static final Nationality MW;
    public static final Nationality MX;
    public static final Nationality MY;
    public static final Nationality MZ;
    public static final Nationality NA;
    public static final Nationality NC;
    public static final Nationality NE;
    public static final Nationality NG;
    public static final Nationality NI;
    public static final Nationality NL;
    public static final Nationality NO;
    public static final Nationality NP;
    public static final Nationality NR;
    public static final Nationality NU;
    public static final Nationality NZ;
    public static final Nationality OM;
    public static final Nationality PA;
    public static final Nationality PE;
    public static final Nationality PF;
    public static final Nationality PG;
    public static final Nationality PH;
    public static final Nationality PK;
    public static final Nationality PL;
    public static final Nationality PR;
    public static final Nationality PS;
    public static final Nationality PT;
    public static final Nationality PW;
    public static final Nationality PY;
    public static final Nationality QA;
    public static final Nationality RE;
    public static final Nationality RO;
    public static final Nationality RS;
    public static final Nationality RU;
    public static final Nationality RW;
    public static final Nationality SA;
    public static final Nationality SC;
    public static final Nationality SD;
    public static final Nationality SE;
    public static final Nationality SG;
    public static final Nationality SI;
    public static final Nationality SK;
    public static final Nationality SL;
    public static final Nationality SM;
    public static final Nationality SN;
    public static final Nationality SO;
    public static final Nationality SR;
    public static final Nationality SS;
    public static final Nationality ST;
    public static final Nationality SV;
    public static final Nationality SY;
    public static final Nationality SZ;
    public static final Nationality TD;
    public static final Nationality TG;
    public static final Nationality TH;
    public static final Nationality TJ;
    public static final Nationality TL;
    public static final Nationality TM;
    public static final Nationality TN;
    public static final Nationality TO;
    public static final Nationality TR;
    public static final Nationality TT;
    public static final Nationality TV;
    public static final Nationality TW;
    public static final Nationality TZ;
    public static final Nationality UA;
    public static final Nationality UG;
    public static final Nationality US;
    public static final Nationality UY;
    public static final Nationality UZ;
    public static final Nationality VC;
    public static final Nationality VE;
    public static final Nationality VN;
    public static final Nationality VU;
    public static final Nationality WS;
    public static final Nationality YE;
    public static final Nationality ZA;
    public static final Nationality ZM;
    public static final Nationality ZW;

    private Nationality(String s, int i)
    {
        super(s, i);
    }

    public static Nationality valueOf(String s)
    {
        return (Nationality)Enum.valueOf(com/etermax/tools/nationality/Nationality, s);
    }

    public static Nationality[] values()
    {
        return (Nationality[])$VALUES.clone();
    }

    static 
    {
        AD = new Nationality("AD", 0);
        AE = new Nationality("AE", 1);
        AF = new Nationality("AF", 2);
        AG = new Nationality("AG", 3);
        AI = new Nationality("AI", 4);
        AL = new Nationality("AL", 5);
        AM = new Nationality("AM", 6);
        AO = new Nationality("AO", 7);
        AR = new Nationality("AR", 8);
        AS = new Nationality("AS", 9);
        AT = new Nationality("AT", 10);
        AU = new Nationality("AU", 11);
        AW = new Nationality("AW", 12);
        AX = new Nationality("AX", 13);
        AZ = new Nationality("AZ", 14);
        BA = new Nationality("BA", 15);
        BB = new Nationality("BB", 16);
        BD = new Nationality("BD", 17);
        BE = new Nationality("BE", 18);
        BF = new Nationality("BF", 19);
        BG = new Nationality("BG", 20);
        BH = new Nationality("BH", 21);
        BI = new Nationality("BI", 22);
        BJ = new Nationality("BJ", 23);
        BL = new Nationality("BL", 24);
        BM = new Nationality("BM", 25);
        BN = new Nationality("BN", 26);
        BO = new Nationality("BO", 27);
        BQ = new Nationality("BQ", 28);
        BR = new Nationality("BR", 29);
        BS = new Nationality("BS", 30);
        BT = new Nationality("BT", 31);
        BW = new Nationality("BW", 32);
        BY = new Nationality("BY", 33);
        BZ = new Nationality("BZ", 34);
        CA = new Nationality("CA", 35);
        CD = new Nationality("CD", 36);
        CF = new Nationality("CF", 37);
        CG = new Nationality("CG", 38);
        CH = new Nationality("CH", 39);
        CI = new Nationality("CI", 40);
        CL = new Nationality("CL", 41);
        CM = new Nationality("CM", 42);
        CN = new Nationality("CN", 43);
        CO = new Nationality("CO", 44);
        CR = new Nationality("CR", 45);
        CU = new Nationality("CU", 46);
        CV = new Nationality("CV", 47);
        CW = new Nationality("CW", 48);
        CY = new Nationality("CY", 49);
        CZ = new Nationality("CZ", 50);
        DE = new Nationality("DE", 51);
        DJ = new Nationality("DJ", 52);
        DK = new Nationality("DK", 53);
        DM = new Nationality("DM", 54);
        DO = new Nationality("DO", 55);
        DZ = new Nationality("DZ", 56);
        EC = new Nationality("EC", 57);
        EE = new Nationality("EE", 58);
        EG = new Nationality("EG", 59);
        EH = new Nationality("EH", 60);
        ER = new Nationality("ER", 61);
        ES = new Nationality("ES", 62);
        ET = new Nationality("ET", 63);
        FI = new Nationality("FI", 64);
        FJ = new Nationality("FJ", 65);
        FM = new Nationality("FM", 66);
        FO = new Nationality("FO", 67);
        FR = new Nationality("FR", 68);
        GA = new Nationality("GA", 69);
        GB = new Nationality("GB", 70);
        GD = new Nationality("GD", 71);
        GE = new Nationality("GE", 72);
        GF = new Nationality("GF", 73);
        GG = new Nationality("GG", 74);
        GH = new Nationality("GH", 75);
        GI = new Nationality("GI", 76);
        GL = new Nationality("GL", 77);
        GM = new Nationality("GM", 78);
        GN = new Nationality("GN", 79);
        GP = new Nationality("GP", 80);
        GQ = new Nationality("GQ", 81);
        GR = new Nationality("GR", 82);
        GT = new Nationality("GT", 83);
        GU = new Nationality("GU", 84);
        GW = new Nationality("GW", 85);
        GY = new Nationality("GY", 86);
        HK = new Nationality("HK", 87);
        HN = new Nationality("HN", 88);
        HR = new Nationality("HR", 89);
        HT = new Nationality("HT", 90);
        HU = new Nationality("HU", 91);
        ID = new Nationality("ID", 92);
        IE = new Nationality("IE", 93);
        IL = new Nationality("IL", 94);
        IN = new Nationality("IN", 95);
        IQ = new Nationality("IQ", 96);
        IR = new Nationality("IR", 97);
        IS = new Nationality("IS", 98);
        IT = new Nationality("IT", 99);
        JE = new Nationality("JE", 100);
        JM = new Nationality("JM", 101);
        JO = new Nationality("JO", 102);
        JP = new Nationality("JP", 103);
        KE = new Nationality("KE", 104);
        KG = new Nationality("KG", 105);
        KH = new Nationality("KH", 106);
        KI = new Nationality("KI", 107);
        KM = new Nationality("KM", 108);
        KN = new Nationality("KN", 109);
        KP = new Nationality("KP", 110);
        KR = new Nationality("KR", 111);
        KW = new Nationality("KW", 112);
        KZ = new Nationality("KZ", 113);
        LA = new Nationality("LA", 114);
        LB = new Nationality("LB", 115);
        LC = new Nationality("LC", 116);
        LI = new Nationality("LI", 117);
        LK = new Nationality("LK", 118);
        LR = new Nationality("LR", 119);
        LS = new Nationality("LS", 120);
        LT = new Nationality("LT", 121);
        LU = new Nationality("LU", 122);
        LV = new Nationality("LV", 123);
        LY = new Nationality("LY", 124);
        MA = new Nationality("MA", 125);
        MC = new Nationality("MC", 126);
        MD = new Nationality("MD", 127);
        ME = new Nationality("ME", 128);
        MG = new Nationality("MG", 129);
        MH = new Nationality("MH", 130);
        MK = new Nationality("MK", 131);
        ML = new Nationality("ML", 132);
        MM = new Nationality("MM", 133);
        MN = new Nationality("MN", 134);
        MO = new Nationality("MO", 135);
        MR = new Nationality("MR", 136);
        MT = new Nationality("MT", 137);
        MU = new Nationality("MU", 138);
        MV = new Nationality("MV", 139);
        MW = new Nationality("MW", 140);
        MX = new Nationality("MX", 141);
        MY = new Nationality("MY", 142);
        MZ = new Nationality("MZ", 143);
        NA = new Nationality("NA", 144);
        NC = new Nationality("NC", 145);
        NE = new Nationality("NE", 146);
        NG = new Nationality("NG", 147);
        NI = new Nationality("NI", 148);
        NL = new Nationality("NL", 149);
        NO = new Nationality("NO", 150);
        NP = new Nationality("NP", 151);
        NR = new Nationality("NR", 152);
        NU = new Nationality("NU", 153);
        NZ = new Nationality("NZ", 154);
        OM = new Nationality("OM", 155);
        PA = new Nationality("PA", 156);
        PE = new Nationality("PE", 157);
        PF = new Nationality("PF", 158);
        PG = new Nationality("PG", 159);
        PH = new Nationality("PH", 160);
        PK = new Nationality("PK", 161);
        PL = new Nationality("PL", 162);
        PR = new Nationality("PR", 163);
        PS = new Nationality("PS", 164);
        PT = new Nationality("PT", 165);
        PW = new Nationality("PW", 166);
        PY = new Nationality("PY", 167);
        QA = new Nationality("QA", 168);
        RE = new Nationality("RE", 169);
        RO = new Nationality("RO", 170);
        RS = new Nationality("RS", 171);
        RU = new Nationality("RU", 172);
        RW = new Nationality("RW", 173);
        SA = new Nationality("SA", 174);
        SC = new Nationality("SC", 175);
        SD = new Nationality("SD", 176);
        SE = new Nationality("SE", 177);
        SG = new Nationality("SG", 178);
        SI = new Nationality("SI", 179);
        SK = new Nationality("SK", 180);
        SL = new Nationality("SL", 181);
        SM = new Nationality("SM", 182);
        SN = new Nationality("SN", 183);
        SO = new Nationality("SO", 184);
        SR = new Nationality("SR", 185);
        SS = new Nationality("SS", 186);
        ST = new Nationality("ST", 187);
        SV = new Nationality("SV", 188);
        SY = new Nationality("SY", 189);
        SZ = new Nationality("SZ", 190);
        TD = new Nationality("TD", 191);
        TG = new Nationality("TG", 192);
        TH = new Nationality("TH", 193);
        TJ = new Nationality("TJ", 194);
        TL = new Nationality("TL", 195);
        TM = new Nationality("TM", 196);
        TN = new Nationality("TN", 197);
        TO = new Nationality("TO", 198);
        TR = new Nationality("TR", 199);
        TT = new Nationality("TT", 200);
        TV = new Nationality("TV", 201);
        TW = new Nationality("TW", 202);
        TZ = new Nationality("TZ", 203);
        UA = new Nationality("UA", 204);
        UG = new Nationality("UG", 205);
        US = new Nationality("US", 206);
        UY = new Nationality("UY", 207);
        UZ = new Nationality("UZ", 208);
        VC = new Nationality("VC", 209);
        VE = new Nationality("VE", 210);
        VN = new Nationality("VN", 211);
        VU = new Nationality("VU", 212);
        WS = new Nationality("WS", 213);
        YE = new Nationality("YE", 214);
        ZA = new Nationality("ZA", 215);
        ZM = new Nationality("ZM", 216);
        ZW = new Nationality("ZW", 217);
        Nationality anationality[] = new Nationality[218];
        anationality[0] = AD;
        anationality[1] = AE;
        anationality[2] = AF;
        anationality[3] = AG;
        anationality[4] = AI;
        anationality[5] = AL;
        anationality[6] = AM;
        anationality[7] = AO;
        anationality[8] = AR;
        anationality[9] = AS;
        anationality[10] = AT;
        anationality[11] = AU;
        anationality[12] = AW;
        anationality[13] = AX;
        anationality[14] = AZ;
        anationality[15] = BA;
        anationality[16] = BB;
        anationality[17] = BD;
        anationality[18] = BE;
        anationality[19] = BF;
        anationality[20] = BG;
        anationality[21] = BH;
        anationality[22] = BI;
        anationality[23] = BJ;
        anationality[24] = BL;
        anationality[25] = BM;
        anationality[26] = BN;
        anationality[27] = BO;
        anationality[28] = BQ;
        anationality[29] = BR;
        anationality[30] = BS;
        anationality[31] = BT;
        anationality[32] = BW;
        anationality[33] = BY;
        anationality[34] = BZ;
        anationality[35] = CA;
        anationality[36] = CD;
        anationality[37] = CF;
        anationality[38] = CG;
        anationality[39] = CH;
        anationality[40] = CI;
        anationality[41] = CL;
        anationality[42] = CM;
        anationality[43] = CN;
        anationality[44] = CO;
        anationality[45] = CR;
        anationality[46] = CU;
        anationality[47] = CV;
        anationality[48] = CW;
        anationality[49] = CY;
        anationality[50] = CZ;
        anationality[51] = DE;
        anationality[52] = DJ;
        anationality[53] = DK;
        anationality[54] = DM;
        anationality[55] = DO;
        anationality[56] = DZ;
        anationality[57] = EC;
        anationality[58] = EE;
        anationality[59] = EG;
        anationality[60] = EH;
        anationality[61] = ER;
        anationality[62] = ES;
        anationality[63] = ET;
        anationality[64] = FI;
        anationality[65] = FJ;
        anationality[66] = FM;
        anationality[67] = FO;
        anationality[68] = FR;
        anationality[69] = GA;
        anationality[70] = GB;
        anationality[71] = GD;
        anationality[72] = GE;
        anationality[73] = GF;
        anationality[74] = GG;
        anationality[75] = GH;
        anationality[76] = GI;
        anationality[77] = GL;
        anationality[78] = GM;
        anationality[79] = GN;
        anationality[80] = GP;
        anationality[81] = GQ;
        anationality[82] = GR;
        anationality[83] = GT;
        anationality[84] = GU;
        anationality[85] = GW;
        anationality[86] = GY;
        anationality[87] = HK;
        anationality[88] = HN;
        anationality[89] = HR;
        anationality[90] = HT;
        anationality[91] = HU;
        anationality[92] = ID;
        anationality[93] = IE;
        anationality[94] = IL;
        anationality[95] = IN;
        anationality[96] = IQ;
        anationality[97] = IR;
        anationality[98] = IS;
        anationality[99] = IT;
        anationality[100] = JE;
        anationality[101] = JM;
        anationality[102] = JO;
        anationality[103] = JP;
        anationality[104] = KE;
        anationality[105] = KG;
        anationality[106] = KH;
        anationality[107] = KI;
        anationality[108] = KM;
        anationality[109] = KN;
        anationality[110] = KP;
        anationality[111] = KR;
        anationality[112] = KW;
        anationality[113] = KZ;
        anationality[114] = LA;
        anationality[115] = LB;
        anationality[116] = LC;
        anationality[117] = LI;
        anationality[118] = LK;
        anationality[119] = LR;
        anationality[120] = LS;
        anationality[121] = LT;
        anationality[122] = LU;
        anationality[123] = LV;
        anationality[124] = LY;
        anationality[125] = MA;
        anationality[126] = MC;
        anationality[127] = MD;
        anationality[128] = ME;
        anationality[129] = MG;
        anationality[130] = MH;
        anationality[131] = MK;
        anationality[132] = ML;
        anationality[133] = MM;
        anationality[134] = MN;
        anationality[135] = MO;
        anationality[136] = MR;
        anationality[137] = MT;
        anationality[138] = MU;
        anationality[139] = MV;
        anationality[140] = MW;
        anationality[141] = MX;
        anationality[142] = MY;
        anationality[143] = MZ;
        anationality[144] = NA;
        anationality[145] = NC;
        anationality[146] = NE;
        anationality[147] = NG;
        anationality[148] = NI;
        anationality[149] = NL;
        anationality[150] = NO;
        anationality[151] = NP;
        anationality[152] = NR;
        anationality[153] = NU;
        anationality[154] = NZ;
        anationality[155] = OM;
        anationality[156] = PA;
        anationality[157] = PE;
        anationality[158] = PF;
        anationality[159] = PG;
        anationality[160] = PH;
        anationality[161] = PK;
        anationality[162] = PL;
        anationality[163] = PR;
        anationality[164] = PS;
        anationality[165] = PT;
        anationality[166] = PW;
        anationality[167] = PY;
        anationality[168] = QA;
        anationality[169] = RE;
        anationality[170] = RO;
        anationality[171] = RS;
        anationality[172] = RU;
        anationality[173] = RW;
        anationality[174] = SA;
        anationality[175] = SC;
        anationality[176] = SD;
        anationality[177] = SE;
        anationality[178] = SG;
        anationality[179] = SI;
        anationality[180] = SK;
        anationality[181] = SL;
        anationality[182] = SM;
        anationality[183] = SN;
        anationality[184] = SO;
        anationality[185] = SR;
        anationality[186] = SS;
        anationality[187] = ST;
        anationality[188] = SV;
        anationality[189] = SY;
        anationality[190] = SZ;
        anationality[191] = TD;
        anationality[192] = TG;
        anationality[193] = TH;
        anationality[194] = TJ;
        anationality[195] = TL;
        anationality[196] = TM;
        anationality[197] = TN;
        anationality[198] = TO;
        anationality[199] = TR;
        anationality[200] = TT;
        anationality[201] = TV;
        anationality[202] = TW;
        anationality[203] = TZ;
        anationality[204] = UA;
        anationality[205] = UG;
        anationality[206] = US;
        anationality[207] = UY;
        anationality[208] = UZ;
        anationality[209] = VC;
        anationality[210] = VE;
        anationality[211] = VN;
        anationality[212] = VU;
        anationality[213] = WS;
        anationality[214] = YE;
        anationality[215] = ZA;
        anationality[216] = ZM;
        anationality[217] = ZW;
        $VALUES = anationality;
    }
}
