// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.etermax.preguntados.datasource.dto.enums;

import com.etermax.a.a;

public final class Country extends Enum
{

    private static final Country $VALUES[];
    public static final Country AD;
    public static final Country AE;
    public static final Country AF;
    public static final Country AG;
    public static final Country AI;
    public static final Country AL;
    public static final Country AM;
    public static final Country AO;
    public static final Country AR;
    public static final Country AS;
    public static final Country AT;
    public static final Country AU;
    public static final Country AW;
    public static final Country AX;
    public static final Country AZ;
    public static final Country BA;
    public static final Country BB;
    public static final Country BD;
    public static final Country BE;
    public static final Country BF;
    public static final Country BG;
    public static final Country BH;
    public static final Country BI;
    public static final Country BJ;
    public static final Country BL;
    public static final Country BM;
    public static final Country BN;
    public static final Country BO;
    public static final Country BQ;
    public static final Country BR;
    public static final Country BS;
    public static final Country BT;
    public static final Country BW;
    public static final Country BY;
    public static final Country BZ;
    public static final Country CA;
    public static final Country CD;
    public static final Country CF;
    public static final Country CG;
    public static final Country CH;
    public static final Country CI;
    public static final Country CL;
    public static final Country CM;
    public static final Country CN;
    public static final Country CO;
    public static final Country CR;
    public static final Country CT;
    public static final Country CU;
    public static final Country CV;
    public static final Country CW;
    public static final Country CY;
    public static final Country CZ;
    public static final Country DE;
    public static final Country DEFAULT_COUNTRY;
    public static final Country DJ;
    public static final Country DK;
    public static final Country DM;
    public static final Country DO;
    public static final Country DZ;
    public static final Country EC;
    public static final Country EE;
    public static final Country EG;
    public static final Country EH;
    public static final Country ER;
    public static final Country ES;
    public static final Country ET;
    public static final Country FI;
    public static final Country FJ;
    public static final Country FM;
    public static final Country FO;
    public static final Country FR;
    public static final Country GA;
    public static final Country GB;
    public static final Country GD;
    public static final Country GE;
    public static final Country GF;
    public static final Country GG;
    public static final Country GH;
    public static final Country GI;
    public static final Country GL;
    public static final Country GM;
    public static final Country GN;
    public static final Country GP;
    public static final Country GQ;
    public static final Country GR;
    public static final Country GT;
    public static final Country GU;
    public static final Country GW;
    public static final Country GX;
    public static final Country GY;
    public static final Country HK;
    public static final Country HN;
    public static final Country HR;
    public static final Country HT;
    public static final Country HU;
    public static final Country ID;
    public static final Country IE;
    public static final Country IL;
    public static final Country IN;
    public static final Country IQ;
    public static final Country IR;
    public static final Country IS;
    public static final Country IT;
    public static final Country JE;
    public static final Country JM;
    public static final Country JO;
    public static final Country JP;
    public static final Country KE;
    public static final Country KG;
    public static final Country KH;
    public static final Country KI;
    public static final Country KM;
    public static final Country KN;
    public static final Country KP;
    public static final Country KR;
    public static final Country KW;
    public static final Country KZ;
    public static final Country LA;
    public static final Country LB;
    public static final Country LC;
    public static final Country LI;
    public static final Country LK;
    public static final Country LR;
    public static final Country LS;
    public static final Country LT;
    public static final Country LU;
    public static final Country LV;
    public static final Country LY;
    public static final Country MA;
    public static final Country MC;
    public static final Country MD;
    public static final Country ME;
    public static final Country MG;
    public static final Country MH;
    public static final Country MK;
    public static final Country ML;
    public static final Country MM;
    public static final Country MN;
    public static final Country MO;
    public static final Country MR;
    public static final Country MT;
    public static final Country MU;
    public static final Country MV;
    public static final Country MW;
    public static final Country MX;
    public static final Country MY;
    public static final Country MZ;
    public static final Country NA;
    public static final Country NC;
    public static final Country NE;
    public static final Country NG;
    public static final Country NI;
    public static final Country NL;
    public static final Country NO;
    public static final Country NP;
    public static final Country NR;
    public static final Country NU;
    public static final Country NZ;
    public static final Country OM;
    public static final Country PA;
    public static final Country PE;
    public static final Country PF;
    public static final Country PG;
    public static final Country PH;
    public static final Country PK;
    public static final Country PL;
    public static final Country PR;
    public static final Country PS;
    public static final Country PT;
    public static final Country PW;
    public static final Country PY;
    public static final Country QA;
    public static final Country RE;
    public static final Country RO;
    public static final Country RS;
    public static final Country RU;
    public static final Country RW;
    public static final Country SA;
    public static final Country SC;
    public static final Country SD;
    public static final Country SE;
    public static final Country SG;
    public static final Country SI;
    public static final Country SK;
    public static final Country SL;
    public static final Country SM;
    public static final Country SN;
    public static final Country SO;
    public static final Country SR;
    public static final Country SS;
    public static final Country ST;
    public static final Country SV;
    public static final Country SY;
    public static final Country SZ;
    public static final Country TD;
    public static final Country TG;
    public static final Country TH;
    public static final Country TJ;
    public static final Country TL;
    public static final Country TM;
    public static final Country TN;
    public static final Country TO;
    public static final Country TR;
    public static final Country TT;
    public static final Country TV;
    public static final Country TW;
    public static final Country TZ;
    public static final Country UA;
    public static final Country UG;
    public static final Country US;
    public static final Country UY;
    public static final Country UZ;
    public static final Country VC;
    public static final Country VE;
    public static final Country VN;
    public static final Country VU;
    public static final Country WS;
    public static final Country YE;
    public static final Country ZA;
    public static final Country ZM;
    public static final Country ZW;

    private Country(String s, int i)
    {
        super(s, i);
    }

    public static Country get(String s, boolean flag)
    {
        if (s != null)
        {
            break MISSING_BLOCK_LABEL_8;
        }
        return DEFAULT_COUNTRY;
        Country country = valueOf(s.toUpperCase());
        return country;
        Exception exception;
        exception;
        if (flag)
        {
            return DEFAULT_COUNTRY;
        } else
        {
            a.a("Language", "error in: ", exception);
            return null;
        }
    }

    public static Country valueOf(String s)
    {
        return (Country)Enum.valueOf(com/etermax/preguntados/datasource/dto/enums/Country, s);
    }

    public static Country[] values()
    {
        return (Country[])$VALUES.clone();
    }

    static 
    {
        GX = new Country("GX", 0);
        CT = new Country("CT", 1);
        AD = new Country("AD", 2);
        AE = new Country("AE", 3);
        AF = new Country("AF", 4);
        AG = new Country("AG", 5);
        AI = new Country("AI", 6);
        AL = new Country("AL", 7);
        AM = new Country("AM", 8);
        AO = new Country("AO", 9);
        AR = new Country("AR", 10);
        AS = new Country("AS", 11);
        AT = new Country("AT", 12);
        AU = new Country("AU", 13);
        AW = new Country("AW", 14);
        AX = new Country("AX", 15);
        AZ = new Country("AZ", 16);
        BA = new Country("BA", 17);
        BB = new Country("BB", 18);
        BD = new Country("BD", 19);
        BE = new Country("BE", 20);
        BF = new Country("BF", 21);
        BG = new Country("BG", 22);
        BH = new Country("BH", 23);
        BI = new Country("BI", 24);
        BJ = new Country("BJ", 25);
        BL = new Country("BL", 26);
        BM = new Country("BM", 27);
        BN = new Country("BN", 28);
        BO = new Country("BO", 29);
        BQ = new Country("BQ", 30);
        BR = new Country("BR", 31);
        BS = new Country("BS", 32);
        BT = new Country("BT", 33);
        BW = new Country("BW", 34);
        BY = new Country("BY", 35);
        BZ = new Country("BZ", 36);
        CA = new Country("CA", 37);
        CD = new Country("CD", 38);
        CF = new Country("CF", 39);
        CG = new Country("CG", 40);
        CH = new Country("CH", 41);
        CI = new Country("CI", 42);
        CL = new Country("CL", 43);
        CM = new Country("CM", 44);
        CN = new Country("CN", 45);
        CO = new Country("CO", 46);
        CR = new Country("CR", 47);
        CU = new Country("CU", 48);
        CV = new Country("CV", 49);
        CW = new Country("CW", 50);
        CY = new Country("CY", 51);
        CZ = new Country("CZ", 52);
        DE = new Country("DE", 53);
        DJ = new Country("DJ", 54);
        DK = new Country("DK", 55);
        DM = new Country("DM", 56);
        DO = new Country("DO", 57);
        DZ = new Country("DZ", 58);
        EC = new Country("EC", 59);
        EE = new Country("EE", 60);
        EG = new Country("EG", 61);
        EH = new Country("EH", 62);
        ER = new Country("ER", 63);
        ES = new Country("ES", 64);
        ET = new Country("ET", 65);
        FI = new Country("FI", 66);
        FJ = new Country("FJ", 67);
        FM = new Country("FM", 68);
        FO = new Country("FO", 69);
        FR = new Country("FR", 70);
        GA = new Country("GA", 71);
        GB = new Country("GB", 72);
        GD = new Country("GD", 73);
        GE = new Country("GE", 74);
        GF = new Country("GF", 75);
        GG = new Country("GG", 76);
        GH = new Country("GH", 77);
        GI = new Country("GI", 78);
        GL = new Country("GL", 79);
        GM = new Country("GM", 80);
        GN = new Country("GN", 81);
        GP = new Country("GP", 82);
        GQ = new Country("GQ", 83);
        GR = new Country("GR", 84);
        GT = new Country("GT", 85);
        GU = new Country("GU", 86);
        GW = new Country("GW", 87);
        GY = new Country("GY", 88);
        HK = new Country("HK", 89);
        HN = new Country("HN", 90);
        HR = new Country("HR", 91);
        HT = new Country("HT", 92);
        HU = new Country("HU", 93);
        ID = new Country("ID", 94);
        IE = new Country("IE", 95);
        IL = new Country("IL", 96);
        IN = new Country("IN", 97);
        IQ = new Country("IQ", 98);
        IR = new Country("IR", 99);
        IS = new Country("IS", 100);
        IT = new Country("IT", 101);
        JE = new Country("JE", 102);
        JM = new Country("JM", 103);
        JO = new Country("JO", 104);
        JP = new Country("JP", 105);
        KE = new Country("KE", 106);
        KG = new Country("KG", 107);
        KH = new Country("KH", 108);
        KI = new Country("KI", 109);
        KM = new Country("KM", 110);
        KN = new Country("KN", 111);
        KP = new Country("KP", 112);
        KR = new Country("KR", 113);
        KW = new Country("KW", 114);
        KZ = new Country("KZ", 115);
        LA = new Country("LA", 116);
        LB = new Country("LB", 117);
        LC = new Country("LC", 118);
        LI = new Country("LI", 119);
        LK = new Country("LK", 120);
        LR = new Country("LR", 121);
        LS = new Country("LS", 122);
        LT = new Country("LT", 123);
        LU = new Country("LU", 124);
        LV = new Country("LV", 125);
        LY = new Country("LY", 126);
        MA = new Country("MA", 127);
        MC = new Country("MC", 128);
        MD = new Country("MD", 129);
        ME = new Country("ME", 130);
        MG = new Country("MG", 131);
        MH = new Country("MH", 132);
        MK = new Country("MK", 133);
        ML = new Country("ML", 134);
        MM = new Country("MM", 135);
        MN = new Country("MN", 136);
        MO = new Country("MO", 137);
        MR = new Country("MR", 138);
        MT = new Country("MT", 139);
        MU = new Country("MU", 140);
        MV = new Country("MV", 141);
        MW = new Country("MW", 142);
        MX = new Country("MX", 143);
        MY = new Country("MY", 144);
        MZ = new Country("MZ", 145);
        NA = new Country("NA", 146);
        NC = new Country("NC", 147);
        NE = new Country("NE", 148);
        NG = new Country("NG", 149);
        NI = new Country("NI", 150);
        NL = new Country("NL", 151);
        NO = new Country("NO", 152);
        NP = new Country("NP", 153);
        NR = new Country("NR", 154);
        NU = new Country("NU", 155);
        NZ = new Country("NZ", 156);
        OM = new Country("OM", 157);
        PA = new Country("PA", 158);
        PE = new Country("PE", 159);
        PF = new Country("PF", 160);
        PG = new Country("PG", 161);
        PH = new Country("PH", 162);
        PK = new Country("PK", 163);
        PL = new Country("PL", 164);
        PR = new Country("PR", 165);
        PS = new Country("PS", 166);
        PT = new Country("PT", 167);
        PW = new Country("PW", 168);
        PY = new Country("PY", 169);
        QA = new Country("QA", 170);
        RE = new Country("RE", 171);
        RO = new Country("RO", 172);
        RS = new Country("RS", 173);
        RU = new Country("RU", 174);
        RW = new Country("RW", 175);
        SA = new Country("SA", 176);
        SC = new Country("SC", 177);
        SD = new Country("SD", 178);
        SE = new Country("SE", 179);
        SG = new Country("SG", 180);
        SI = new Country("SI", 181);
        SK = new Country("SK", 182);
        SL = new Country("SL", 183);
        SM = new Country("SM", 184);
        SN = new Country("SN", 185);
        SO = new Country("SO", 186);
        SR = new Country("SR", 187);
        SS = new Country("SS", 188);
        ST = new Country("ST", 189);
        SV = new Country("SV", 190);
        SY = new Country("SY", 191);
        SZ = new Country("SZ", 192);
        TD = new Country("TD", 193);
        TG = new Country("TG", 194);
        TH = new Country("TH", 195);
        TJ = new Country("TJ", 196);
        TL = new Country("TL", 197);
        TM = new Country("TM", 198);
        TN = new Country("TN", 199);
        TO = new Country("TO", 200);
        TR = new Country("TR", 201);
        TT = new Country("TT", 202);
        TV = new Country("TV", 203);
        TW = new Country("TW", 204);
        TZ = new Country("TZ", 205);
        UA = new Country("UA", 206);
        UG = new Country("UG", 207);
        US = new Country("US", 208);
        UY = new Country("UY", 209);
        UZ = new Country("UZ", 210);
        VC = new Country("VC", 211);
        VE = new Country("VE", 212);
        VN = new Country("VN", 213);
        VU = new Country("VU", 214);
        WS = new Country("WS", 215);
        YE = new Country("YE", 216);
        ZA = new Country("ZA", 217);
        ZM = new Country("ZM", 218);
        ZW = new Country("ZW", 219);
        Country acountry[] = new Country[220];
        acountry[0] = GX;
        acountry[1] = CT;
        acountry[2] = AD;
        acountry[3] = AE;
        acountry[4] = AF;
        acountry[5] = AG;
        acountry[6] = AI;
        acountry[7] = AL;
        acountry[8] = AM;
        acountry[9] = AO;
        acountry[10] = AR;
        acountry[11] = AS;
        acountry[12] = AT;
        acountry[13] = AU;
        acountry[14] = AW;
        acountry[15] = AX;
        acountry[16] = AZ;
        acountry[17] = BA;
        acountry[18] = BB;
        acountry[19] = BD;
        acountry[20] = BE;
        acountry[21] = BF;
        acountry[22] = BG;
        acountry[23] = BH;
        acountry[24] = BI;
        acountry[25] = BJ;
        acountry[26] = BL;
        acountry[27] = BM;
        acountry[28] = BN;
        acountry[29] = BO;
        acountry[30] = BQ;
        acountry[31] = BR;
        acountry[32] = BS;
        acountry[33] = BT;
        acountry[34] = BW;
        acountry[35] = BY;
        acountry[36] = BZ;
        acountry[37] = CA;
        acountry[38] = CD;
        acountry[39] = CF;
        acountry[40] = CG;
        acountry[41] = CH;
        acountry[42] = CI;
        acountry[43] = CL;
        acountry[44] = CM;
        acountry[45] = CN;
        acountry[46] = CO;
        acountry[47] = CR;
        acountry[48] = CU;
        acountry[49] = CV;
        acountry[50] = CW;
        acountry[51] = CY;
        acountry[52] = CZ;
        acountry[53] = DE;
        acountry[54] = DJ;
        acountry[55] = DK;
        acountry[56] = DM;
        acountry[57] = DO;
        acountry[58] = DZ;
        acountry[59] = EC;
        acountry[60] = EE;
        acountry[61] = EG;
        acountry[62] = EH;
        acountry[63] = ER;
        acountry[64] = ES;
        acountry[65] = ET;
        acountry[66] = FI;
        acountry[67] = FJ;
        acountry[68] = FM;
        acountry[69] = FO;
        acountry[70] = FR;
        acountry[71] = GA;
        acountry[72] = GB;
        acountry[73] = GD;
        acountry[74] = GE;
        acountry[75] = GF;
        acountry[76] = GG;
        acountry[77] = GH;
        acountry[78] = GI;
        acountry[79] = GL;
        acountry[80] = GM;
        acountry[81] = GN;
        acountry[82] = GP;
        acountry[83] = GQ;
        acountry[84] = GR;
        acountry[85] = GT;
        acountry[86] = GU;
        acountry[87] = GW;
        acountry[88] = GY;
        acountry[89] = HK;
        acountry[90] = HN;
        acountry[91] = HR;
        acountry[92] = HT;
        acountry[93] = HU;
        acountry[94] = ID;
        acountry[95] = IE;
        acountry[96] = IL;
        acountry[97] = IN;
        acountry[98] = IQ;
        acountry[99] = IR;
        acountry[100] = IS;
        acountry[101] = IT;
        acountry[102] = JE;
        acountry[103] = JM;
        acountry[104] = JO;
        acountry[105] = JP;
        acountry[106] = KE;
        acountry[107] = KG;
        acountry[108] = KH;
        acountry[109] = KI;
        acountry[110] = KM;
        acountry[111] = KN;
        acountry[112] = KP;
        acountry[113] = KR;
        acountry[114] = KW;
        acountry[115] = KZ;
        acountry[116] = LA;
        acountry[117] = LB;
        acountry[118] = LC;
        acountry[119] = LI;
        acountry[120] = LK;
        acountry[121] = LR;
        acountry[122] = LS;
        acountry[123] = LT;
        acountry[124] = LU;
        acountry[125] = LV;
        acountry[126] = LY;
        acountry[127] = MA;
        acountry[128] = MC;
        acountry[129] = MD;
        acountry[130] = ME;
        acountry[131] = MG;
        acountry[132] = MH;
        acountry[133] = MK;
        acountry[134] = ML;
        acountry[135] = MM;
        acountry[136] = MN;
        acountry[137] = MO;
        acountry[138] = MR;
        acountry[139] = MT;
        acountry[140] = MU;
        acountry[141] = MV;
        acountry[142] = MW;
        acountry[143] = MX;
        acountry[144] = MY;
        acountry[145] = MZ;
        acountry[146] = NA;
        acountry[147] = NC;
        acountry[148] = NE;
        acountry[149] = NG;
        acountry[150] = NI;
        acountry[151] = NL;
        acountry[152] = NO;
        acountry[153] = NP;
        acountry[154] = NR;
        acountry[155] = NU;
        acountry[156] = NZ;
        acountry[157] = OM;
        acountry[158] = PA;
        acountry[159] = PE;
        acountry[160] = PF;
        acountry[161] = PG;
        acountry[162] = PH;
        acountry[163] = PK;
        acountry[164] = PL;
        acountry[165] = PR;
        acountry[166] = PS;
        acountry[167] = PT;
        acountry[168] = PW;
        acountry[169] = PY;
        acountry[170] = QA;
        acountry[171] = RE;
        acountry[172] = RO;
        acountry[173] = RS;
        acountry[174] = RU;
        acountry[175] = RW;
        acountry[176] = SA;
        acountry[177] = SC;
        acountry[178] = SD;
        acountry[179] = SE;
        acountry[180] = SG;
        acountry[181] = SI;
        acountry[182] = SK;
        acountry[183] = SL;
        acountry[184] = SM;
        acountry[185] = SN;
        acountry[186] = SO;
        acountry[187] = SR;
        acountry[188] = SS;
        acountry[189] = ST;
        acountry[190] = SV;
        acountry[191] = SY;
        acountry[192] = SZ;
        acountry[193] = TD;
        acountry[194] = TG;
        acountry[195] = TH;
        acountry[196] = TJ;
        acountry[197] = TL;
        acountry[198] = TM;
        acountry[199] = TN;
        acountry[200] = TO;
        acountry[201] = TR;
        acountry[202] = TT;
        acountry[203] = TV;
        acountry[204] = TW;
        acountry[205] = TZ;
        acountry[206] = UA;
        acountry[207] = UG;
        acountry[208] = US;
        acountry[209] = UY;
        acountry[210] = UZ;
        acountry[211] = VC;
        acountry[212] = VE;
        acountry[213] = VN;
        acountry[214] = VU;
        acountry[215] = WS;
        acountry[216] = YE;
        acountry[217] = ZA;
        acountry[218] = ZM;
        acountry[219] = ZW;
        $VALUES = acountry;
        DEFAULT_COUNTRY = GX;
    }
}
